# Generated by Django 3.0.3 on 2020-11-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('fips', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PennHospitals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
                ('aii_avail', models.IntegerField()),
                ('aii_total', models.IntegerField()),
                ('icu_avail', models.IntegerField()),
                ('icu_total', models.IntegerField()),
                ('med_avail', models.IntegerField()),
                ('med_total', models.IntegerField()),
                ('covid_patients', models.IntegerField()),
                ('aii_percent', models.FloatField()),
                ('icu_percent', models.FloatField()),
                ('med_percent', models.FloatField()),
            ],
            options={
                'unique_together': {('date', 'county')},
            },
        ),
        migrations.CreateModel(
            name='PennDeaths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
                ('population', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('deaths_cume', models.IntegerField()),
                ('deaths_rate', models.FloatField()),
                ('deaths_cume_rate', models.FloatField()),
            ],
            options={
                'unique_together': {('date', 'county')},
            },
        ),
        migrations.CreateModel(
            name='PennCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
                ('cases', models.IntegerField()),
                ('cases_avg_new', models.FloatField()),
                ('cases_cume', models.IntegerField()),
                ('population', models.IntegerField()),
                ('cases_rate', models.FloatField()),
                ('cases_avg_new_rate', models.FloatField()),
                ('cases_cume_rate', models.IntegerField()),
            ],
            options={
                'unique_together': {('date', 'county')},
            },
        ),
        migrations.CreateModel(
            name='MetricsActNow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('county', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('fips', models.CharField(max_length=128)),
                ('testPositivityRatio', models.FloatField()),
                ('infectionRate', models.FloatField()),
            ],
            options={
                'unique_together': {('date', 'county')},
            },
        ),
        migrations.CreateModel(
            name='CasesDeathsNTY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('county', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('fips', models.CharField(max_length=128, null=True)),
                ('cases', models.IntegerField(null=True)),
                ('deaths', models.IntegerField(null=True)),
                ('confirmed_cases', models.IntegerField(null=True)),
                ('confirmed_deaths', models.IntegerField(null=True)),
                ('probable_cases', models.IntegerField(null=True)),
                ('probable_deaths', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('date', 'county')},
            },
        ),
    ]
