# Generated by Django 3.0.3 on 2020-11-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PennCaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
                ('cases', models.IntegerField()),
                ('cases_avg_new', models.FloatField()),
                ('cases_cume', models.IntegerField()),
                ('population', models.IntegerField()),
                ('cases_rate', models.FloatField()),
                ('cases_avg_new_rate', models.FloatField()),
                ('cases_cume_rate', models.IntegerField()),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
