# Generated by Django 3.0.3 on 2020-11-28 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='casesdeathsnty',
            unique_together={('date', 'fips')},
        ),
        migrations.AlterUniqueTogether(
            name='metricsactnow',
            unique_together={('date', 'fips')},
        ),
    ]
