# Generated by Django 3.0.3 on 2020-11-25 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penncasedata',
            name='modified_date',
        ),
    ]
