# Generated by Django 3.0.3 on 2020-11-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0002_auto_20201128_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pennhospitals',
            name='aii_avail',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pennhospitals',
            name='aii_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pennhospitals',
            name='aii_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pennhospitals',
            name='covid_patients',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pennhospitals',
            name='icu_avail',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pennhospitals',
            name='icu_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pennhospitals',
            name='icu_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pennhospitals',
            name='med_avail',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pennhospitals',
            name='med_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pennhospitals',
            name='med_total',
            field=models.IntegerField(null=True),
        ),
    ]
