# Generated by Django 3.0.3 on 2020-11-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0002_remove_penncasedata_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penncasedata',
            name='cases_avg_new',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='penncasedata',
            name='cases_avg_new_rate',
            field=models.FloatField(null=True),
        ),
    ]
