# Generated by Django 3.0.3 on 2020-11-28 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0003_auto_20201128_0350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casesdeathsnty',
            name='confirmed_cases',
        ),
        migrations.RemoveField(
            model_name='casesdeathsnty',
            name='confirmed_deaths',
        ),
        migrations.RemoveField(
            model_name='casesdeathsnty',
            name='probable_cases',
        ),
        migrations.RemoveField(
            model_name='casesdeathsnty',
            name='probable_deaths',
        ),
    ]
