# Generated by Django 3.0.3 on 2020-11-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0003_auto_20201125_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penncasedata',
            name='cases_avg_new',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='penncasedata',
            name='cases_avg_new_rate',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
