# Generated by Django 3.0.3 on 2020-11-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0004_auto_20201125_0253'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='penncasedata',
            unique_together={('date', 'county')},
        ),
    ]
