# Generated by Django 3.0.3 on 2020-11-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0005_auto_20201125_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penncasedata',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
